# Generated by Django 5.1.6 on 2026-06-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('web_app', 'Web Application'), ('mobile_app', 'Mobile Application'), ('api', 'API'), ('database', 'Database'), ('server', 'Server'), ('network_device', 'Network Device'), ('desktop_app', 'Desktop Application'), ('cloud_service', 'Cloud Service')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('business_owner', models.CharField(blank=True, max_length=150)),
                ('technology_stack', models.TextField(blank=True)),
                ('production_url', models.URLField(blank=True)),
                ('staging_url', models.URLField(blank=True)),
                ('repository_url', models.URLField(blank=True)),
                ('server_ip', models.CharField(blank=True, max_length=50)),
                ('database_name', models.CharField(blank=True, max_length=100)),
                ('criticality', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL)),
                ('project_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to=settings.AUTH_USER_MODEL)),
                ('security_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_assets', to='teams.team')),
                ('software_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_assets', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
