# Generated by Django 5.1.6 on 2026-06-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
