# Generated by Django 5.1.6 on 2026-06-29 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_asset_domain_asset_request_id'),
        ('vulnerabilities', '0003_vulnerability_auto_close_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('bug_created', 'Bug Created'), ('bug_assigned', 'Bug Assigned'), ('bug_reassigned', 'Bug Reassigned'), ('bug_status_changed', 'Status Changed'), ('bug_resolved', 'Bug Resolved'), ('bug_waiting_auto_close', 'Waiting for Auto Close'), ('bug_auto_closed', 'Bug Auto Closed'), ('bug_reopened', 'Bug Reopened'), ('bug_closed', 'Bug Closed'), ('bug_overdue', 'Bug Overdue'), ('critical_bug_created', 'Critical Bug Created'), ('comment_added', 'Comment Added'), ('evidence_uploaded', 'Evidence Uploaded'), ('retest_required', 'Retest Required'), ('retest_failed', 'Retest Failed'), ('retest_passed', 'Retest Passed'), ('auto_close_reminder', 'Auto Close Reminder'), ('system_alert', 'System Alert')], max_length=50)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='assets.asset')),
                ('related_vulnerability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='vulnerabilities.vulnerability')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
