# Generated by Django 5.1.6 on 2026-06-29 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('bug_type', models.CharField(choices=[('sql_injection', 'SQL Injection'), ('xss', 'Cross Site Scripting'), ('broken_access_control', 'Broken Access Control'), ('insecure_direct_object_reference', 'Insecure Direct Object Reference'), ('authentication_bypass', 'Authentication Bypass'), ('sensitive_data_exposure', 'Sensitive Data Exposure'), ('weak_password_policy', 'Weak Password Policy'), ('missing_rate_limit', 'Missing Rate Limit'), ('security_misconfiguration', 'Security Misconfiguration'), ('vulnerable_component', 'Vulnerable Component'), ('file_upload_vulnerability', 'File Upload Vulnerability'), ('business_logic_flaw', 'Business Logic Flaw'), ('api_security_issue', 'API Security Issue'), ('server_misconfiguration', 'Server Misconfiguration'), ('network_security_issue', 'Network Security Issue'), ('other', 'Other')], max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('informational', 'Informational')], max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=20)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('affected_url', models.URLField(blank=True)),
                ('affected_parameter', models.CharField(blank=True, max_length=300)),
                ('steps_to_reproduce', models.TextField(blank=True)),
                ('impact', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('fixed', 'Fixed'), ('ready_for_retest', 'Ready for Retest'), ('retesting', 'Retesting'), ('verified_fixed', 'Verified Fixed'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('rejected', 'Rejected'), ('risk_accepted', 'Risk Accepted')], default='new', max_length=50)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='assets.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vulnerabilities', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_vulnerabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('partially_fixed', 'Partially Fixed')], max_length=50)),
                ('note', models.TextField(blank=True)),
                ('retest_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retest_results', to='vulnerabilities.vulnerability')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vulnerabilities.vulnerability')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidences/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='vulnerabilities.vulnerability')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='vulnerabilities.vulnerability')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
